language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nox
  - pip install codecov
# command to run tests
script: 
  - nox
  - codecov
